site_name: Graphene Django CRUDDALS

# readthedocs theme
# mkdocs

docs_dir: docs

theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true

repo_url: https://github.com/juanjcardona13/graphene_django_cruddals

edit_uri: tree/main/docs/docs

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [..]

extra:
  edit_on_github: true

extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.extra
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      baselevel: 1
      separator: "-"

nav:
  - Home: index.md
  - GET STARTED:
    -  ğŸ Quick Start: GET-STARTED/Quick-Start.md
    -  âš™ï¸ Installation: GET-STARTED/Installation.md

  - GUIDE TUTORIALS:
    -  ğŸ’¡ Basic Usage: GUIDE-TUTORIALS/Basic-Usage.md
    -  ğŸ“ Advance Usage: GUIDE-TUTORIALS/Advance-Usage.md
    -  ğŸŒŸ Features: GUIDE-TUTORIALS/Features.md

  - API REFERENCE:
    -  ğŸ› ï¸ Django Model : API-REFERENCE/django-model-cruddals.md
    -  ğŸ› ï¸ Django App : API-REFERENCE/django-app-cruddals.md
    -  ğŸ› ï¸ Django Project : API-REFERENCE/django-project-cruddals.md
