site_name: Graphene Django CRUDDALS
site_description: Graphene Django CRUDDALS Convert your Django models into a complete GraphQL API with all CRUD operations + DALS operations (Activate, Deactivate, List, Search)
theme:
  name: material
  logo: img/logoFullWhite.svg
  favicon: img/logoWhite.png
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      primary: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

repo_name: juanjcardona13/graphene_django_cruddals
repo_url: https://github.com/juanjcardona13/graphene_django_cruddals
edit_uri: tree/main/docs/docs
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [..]

extra:
  edit_on_github: true

extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.extra
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      baselevel: 1
      separator: "-"

nav:
  - Home: index.md
  - GET STARTED:
    -  ğŸ Quick Start: get-started/quick-start.md
    -  âš™ï¸ Installation: get-started/installation.md

  - GUIDE TUTORIALS:
    -  ğŸ’¡ Basic Usage: guide-tutorials/basic-usage.md
    -  ğŸ“ Advance Usage: guide-tutorials/advance-usage.md
    -  ğŸŒŸ Features: guide-tutorials/features.md

  - API REFERENCE:
    -  ğŸ› ï¸ Django Model : api-reference/django-model-cruddals.md
    -  ğŸ› ï¸ Django App : api-reference/django-app-cruddals.md
    -  ğŸ› ï¸ Django Project : api-reference/django-project-cruddals.md

docs_dir: docs

# readthedocs theme
# mkdocs