site_name: Graphene Django CRUDDALS

theme: readthedocs

repo_url: https://github.com/juanjcardona13/graphene_django_cruddals

edit_uri: tree/main/docs/docs

plugins:
  - search
  - mkdocstrings

extra:
  edit_on_github: true 

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 1
      separator: "-"


nav:
  - Home: index.md
  - GET STARTED:
    -  ğŸ Quick Start: GET STARTED/Quick-Start.md
    - âš™ï¸ Installation: GET STARTED/Installation.md
  
  - GUIDE TUTORIALS:
    -  ğŸ’¡ Basic Usage: GUIDE-TUTORIALS/Basic-Usage.md
    -  ğŸ“ Advance Usage: GUIDE-TUTORIALS/Advance-Usage.md
    -  ğŸŒŸ Features: GUIDE-TUTORIALS/Features.md

  - API:
    -  ğŸ› ï¸ Custom Types: API/Custom-Types.md




  






